### ISSUE TITLE
Command Permissions

### ISSUE THREAD

**Issue by xhyrom** [Mr-Infinity-Bot/bucket#1]
# What
The bot will stop using permission checking in the normal way, and when connecting to a new server the permission for commands will automatically be set to permission like `BAN_MEMBERS`, but people will be able to add roles/users.

# Images
![obrázok](https://user-images.githubusercontent.com/56601352/146799835-fae1b45a-84dc-4e25-915a-d40e52b4ad81.png)
![obrázok](https://user-images.githubusercontent.com/56601352/146799842-e941654f-924a-47dd-968d-bf90229be721.png)

**Comment by xhyrom** [comment]
![obrázok](https://user-images.githubusercontent.com/56601352/146799939-1f875979-38bd-45d1-a5cf-2ae108c53d87.png)

**Comment by fiifa** [comment]
Nice.

**Comment by xhyrom** [comment]
in canary (stable soon)
